---
geometry       : vmargin=1.0in, hmargin=0.75in
bibliography   : refs/bib/span420.bib
csl            : refs/bib/apa.csl
output:
  pdf_document:
    toc: no
    highlight: pygments
    includes:
      in_header: header.tex
---

01:940:420:01 - Spring 2022  
Meetings: MU 208, 17:40--19:00  

Professor: Joseph V. Casillas, PhD  
Email: \href{mailto:joseph.casillas@rutgers.edu}{joseph.casillas@rutgers.edu}  
Office: AB 5174  
Office hours: by appointment



# Course description

This course serves as an introduction to the field of second language acquisition (SLA) and teaching. It presents an overview of SLA research with an emphasis on four different areas: 1) pedagogy 2) use 3) analysis and 4) processes. Successful completion of the course will allow the student to demonstrate familiarity with basic concepts of each of the four areas, with a special focus on issues related to language contact, bilingualism, and research methodology. Students will also design and implement an original research project.  

Pre-requisites: SPAN 361 or 363

# Materials

## Class websites

- Course website: [www.span420.jvcasillas.com](https://www.span420.jvcasillas.com)
- Articles and chapters on [Canvas][3]

## Text books

1. Koike, D. A., & Klee, C. (2013). [Lingüística aplicada: Adquisición del español como segunda lengua][1]. New York: Wiley. ISBN: 978-1-118-40799-8. 
2. Grosjean, F., & Li, P. (2012). [The psycholinguistics of bilingualism][2]. John Wiley & Sons.  
ISBN: 978-1-4443-3279-7.
3. Journal articles, chapters. Available on [Canvas][3]

[1]: http://www.wiley.com/WileyCDA/WileyTitle/productCd-EHEP002421.html
[2]: http://www.wiley.com/WileyCDA/WileyTitle/productCd-EHEP002792.html
[3]: https://rutgers.instructure.com/courses/162767


# Coursework

## Evaluation

\begin{center}
\begin{tabular}{lrp{0.75in}lr}
\toprule
Component                     & Percentage & & \multicolumn{2}{c}{Grade distribution} \\
\cmidrule(lr){1-2}
\cmidrule(lr){4-5}
Preparation, participation, misc. hw & 15\%       & & A  & 92--100 \\
Area essay 1                         & 15\%       & & B+ & 87--91  \\
Area essay 2                         & 15\%       & & B  & 80--86  \\
Presentation 1                       & 15\%       & & C+ & 77--79  \\
Presentation 2                       & 15\%       & & C  & 70--76  \\
Final project                        & 25\%       & & D  & 65--69  \\
 - written                           &            & & F  & 0--64   \\
 - presentation                      &            & &    &         \\
\bottomrule
\end{tabular}
\end{center}

## Participation and homework

Students are expected to attend class prepared and participate actively. Satisfactory preparation implies having read the assigned reading and completing necessary homework beforehand. 
Satisfactory participation implies asking questions, taking part in class discussion, and showing general understanding of the relevant material. 
The assigned readings are difficult and will require time and effort.

## Presentations

There will be 8 student led class presentations, 2 for each area. 
Students are required to present one time each with a partner. 
Presentation order and assignments will be established during the first weeks of class. 
The student responsible for leading discussion should prepare slides, handouts, and questions/ideas to foment participation amongst peers. 
Groups are encouraged to use slack before and after the presentation for discussion and to share resources. 
The presentation materials must be shared with the professor the night before the actual presentation.

## Area essays

At the end of each module there will be a writing assignment in the form of a short essay. 
Each student must complete two of the four essays. 
There will be specific instructions given the week before the essay is due.

## Final project

Each student will complete a research project related to one of the four areas. 
All projects require the prior approval of the professor. 
Projects are due on the day and time of the university assigned final exam (though there is no exam). 
Students will present their work in a semi-finished state during the final two weeks of the semester (10 min. presentation + 5 min. for questions). 
Students are encouraged to begin thinking about their topic from the beginning of the semester, and work with the professor to ensure that it is appropriate. 
Possible ideas:

- Pedagogy
    - Teaching portfolios
    - Classroom observations and analyses
    - Technology in the classroom
- Use
    - Sociolinguistic interview
    - Spanish in U.S., New Jersey
    - 3rd language acquisition
- Analysis/Processes
    - Participation in university approved research
    - Original research
    - Etc.


# Department rules and course policy

The course is designed to satisfy the learning goals of the Department of Spanish and Portuguese. 
More information available at: http://span-port.rutgers.edu/learning-goals

### Communication 

All course communication will be via Slack. 
You should have received an email with an invitation link to join the course Slack. 
Some rules for using Slack:

- Use an identifiable username and add your picture to your profile.
- Only the professor is allowed to use the **\@channel** and **\@here** mentions.
- While this is an informal communication channel, all rules of academic discourse apply.
- Ask and answer questions on the appropriate channel.
- Create channels as needed, especially for group presentations.

### Attendance

Regular class attendance is essential for successful completion of the course. 
More than 4 absences will have a negative effect on your final grade. 
Arriving to class ten minutes late is considered an absence. 
The 4th absence and every subsequent absence after that will result in the loss of 5\% point off the final overall course grade, regardless of reason. 
Keep in mind that while you have 3 "free" absences, on the day/s you miss you will not be able to earn participation points, and you will miss the material given in class. 
If you are absent, contact a classmate immediately to get the assignments and to keep up with the material scheduled in the syllabus. 
The instructor is not responsible to put you up to date. 
Do not send emails to the instructor asking for updates if you missed class (i.e. "I was absent today. Did we do anything important?"). 
More information regarding the university policy on self-reporting absences is available here: https://sims.rutgers.edu/ssra/

Any planned absence that you are aware of ahead of time, such as religious  holidays recognized by Rutgers University or Dean's excuses, should be made up before the absence occurs. 
If you know that you will be absent, it is your responsibility to let the instructor know ahead of time. 
All holidays or special events observed by any religion will be honored for those students who show affiliation with that particular religion. 
Absences pre-approved by the RU Dean of Students (or Dean's designee) will be honored. 
More information available here: https://scheduling.rutgers.edu/scheduling/religious-holiday-policy

### Code of academic integrity

The professor will initiate an academic integrity case against students suspected of cheating, plagiarizing, or aiding others in dishonest academic behavior. 
Students are responsible for reading and understanding the Code of Academic Integrity.

Examples of academic dishonesty include, but are not limited to, plagiarism,  cheating, and aiding and abetting dishonesty. 
An example of plagiarism would be to submit a written sample which in part or in whole is not the student's own work without attributing the source. 
Cheating includes allowing another person to do your work and to submit the work under one's own name. 
Any work which is submitted for a grade must be 100% the student's own work. 
If you are not sure when it is appropriate to seek help, please see the professor.

\vspace{0.2in}
\hrule  
\textcolor{RUred}{Plagiarism} is the use of another person’s words, ideas, or results without giving that person appropriate credit. 
Do not plagiarize.

\scriptsize{Rutgers University Academic Integrity Policy: http://academicintegrity.rutgers.edu/}
\vspace{.1in}
\hrule

\vspace{0.3in}
\normalsize

For more information 

- http://academicintegrity.rutgers.edu/ 
- http://www.libraries.rutgers.edu/avoid_plagiarism. 


### Students with disabilities

Rutgers University welcomes students with disabilities into all of the University's educational programs. 
In order to receive consideration for reasonable accommodations, a student with a disability must contact the appropriate disability services office at the campus where you are officially enrolled, participate in an intake interview, and provide documentation:  [https://ods.rutgers.edu/students/documentation-guidelines](https://ods.rutgers.edu/students/documentation-guidelines). 

If the documentation supports your request for reasonable accommodations, your campus's disability services office will provide you with a Letter of Accommodations.
Please share this letter with your instructors and discuss the accommodations with them as early in your courses as possible. 
To begin this process, please complete the Registration form on the ODS web site at:  
[https://ods.rutgers.edu/students/registration-form](https://ods.rutgers.edu/students/registration-form).

----

\vspace{.2in}

```{r, temario-420, child="./temario/temario_s2022.Rmd"}
```
